language: php

php:
    - 5.5
    - 5.6

install: composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --coverage-text

after_script: vendor/bin/coveralls -v --exclude-no-stmt
